### ISSUE TITLE
--clone-content is not optional

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/circleci-orb#34]
See https://github.com/pantheon-systems/circleci-orb/blob/master/src/%40orb.yml#L107

Users can not opt-out of `--clone-content`, which means the `dev` DB and files are copied to the multidev on each code push. This is an issue if there are existing changes to the DB on the multidev, as they are overwritten.

**Comment by stevector** [comment]
Done in https://github.com/pantheon-systems/circleci-orb/pull/44!
