### ISSUE TITLE
Pantheon Push Hangs on SSH key add

### ISSUE THREAD

**Issue by dbdoyle182** [pantheon-systems/circleci-orb#35]
Hello pantheon folks,

When I run my build it hangs immediately following the initialization of the git repository in /tmp/pantheon_repo/.git. I get the warning about permanently adding the key to the list of known hosts and then it appears to prompt for the hosts password. After that it hangs, has anyone else run into this issue?

**Comment by stevector** [comment]
Hi @dbdoyle182, Thanks for trying our Orb!

That behavior occurs when the ssh keys are not configured between CircleCI and Pantheon (step 3 in the README set up). Do you have the public key added to a Pantheon account and the private key in your CircleCI configuration?

**Comment by dbdoyle182** [comment]
The keys were not matching! Got it fixed, thanks.
