### ISSUE TITLE
Document env vars needed when retrofitting to existing non-build-tools sites

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/circleci-orb#68]
I've retrofitted this orb into a few sites run via Bitbucket + CircleCI + Pantheon that were using home-grown "Build tools inspired" CircleCI scripts that had become too cumbersome to maintain and slow in builds. It mostly worked flawlessly except that the Build Tools commands being used by the push command need to interact with the Bitbucket API to perform branch deletion tasks. These API calls were failing because I had not set the `BITBUCKET_USER` and `BITBUCKET_PASS` environment variables in CircleCI. Adding these env vars seems to have resolved the problem, but I had to go hunting in the code of the build tools plugin to discover what I was missing. I recommend adding these (and likely the `GITHUB_TOKEN` for users on GIthub, etc) to the readme to ensure retrofitters such as myself don't run into similar headaches.

**Comment by kporras07** [comment]
Hi @dustinleblanc now that the info is fresh in your mind, would you mind drafting a PR with that info and we could come back later and fill in the Github part? That would be super appreciated!

**Comment by dustinleblanc** [comment]
Sure!

**Comment by dustinleblanc** [comment]
quick PR opened!

**Comment by rwagner00** [comment]
@dustinleblanc PR was merged and github auto-closed this issue. Can it stay closed or does it need to be re-opened?

**Comment by dustinleblanc** [comment]
My personal need is well documented now, but the team may want to consider re-opening to document similar configuration needs, or opening a follow up issue to do so
